### PR TITLE
Update group publication list

### PR DESCRIPTION
**Pull request by osanstrong**
## Summary of changes

This PR updates the group publication list on the website with new publications, and adds pdf copies of several papers, reports, and proceedings for display.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issues and PRs

- Issue: #279 

## Associated Developers

- Dev: @katyhuff 

## Checklist for Reviewers

Reviewers should use [this link](/manual/guides/pull_requests.md) to get to the 
Review Checklist before they begin their review.

### CODE REVIEW

**Comment by abachma2** [comment]
Hi @osanstrong, thanks for working on this. It looks like a lot of new PDFs have been added to the repo. Are there that many new papers to add to the website? I just want to make sure that the repo and git log doesn't get cluttered with duplicate files.

**Comment by osanstrong** [comment]
Hi @abachma2, most of the new PDFs are PDF uploads of papers which were already listed but lacked a PDF copy; if updating files of already-listed publications is out of scope for this request, I can move it to its own PR.

As for the bachmann_empirical_2020 and bachmann_comparison_2021, if those were with a different institution that's a mistake on my end, and I will also check for/remove other additions which were published around the time of a member joining/leaving ARFC but do not clearly relate to the group.

**Comment by abachma2** [comment]
I think adding the PDFs is within the scope of this PR. I just wanted to make sure all of the files were necessary, because it's a lot. And yes, if you can take some time (I know it'll be a good bit of time) to double check that everything you've added pertains to ARFC, that would be great!

**Comment by osanstrong** [comment]
I just unstaged a bunch which I had added because they were from around when a publisher was in the group, but in hindsight, did not seem related to the group.

I'll check again later, but that leaves substantially fewer publications to add.

**Comment by osanstrong** [comment]
I was going through and deleting pdfs in a few batches from commit history, and despite best efforts, I think on the last batch I accidentally purged one that was already in the website somewhere (hence why a bunch of modifications of earlier commits suddenly popped up). 

I think I'm going to manually rebase these additions in a new branch and PR that.

**Comment by abachma2** [comment]
I would definitely see if you can sit down with someone in the group and go through what git commands you made, and figure out how to fix some of this. I know @katyhuff prefers to use `merge` instead of `rebase` in the group.

**Comment by osanstrong** [comment]
Indeed; I spoke with Professor Huff this morning on the topic, and I realize I misspoke in that comment: I do not plan on using git `rebase` , rather, that I would manually make the same/net changes in a new branch, which I am about to submit a new PR for. (mentioning this PR and the original issue)

**Pull request closed without merging**
