### PR TITLE
Add workflow to autodeploy site

### LINKED ISSUE #247: Feature: Website CD via GitHub Actions
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

## Expected Behavior
The website should update automatically when changes are pushed to the `source` branch

## Actual Behavior
This does not happen

## Steps to Reproduce the Problem

  1. Look at the current state of the `source` branch
  1. Look at the current state of the `master` branch
  2. Notice how the arfc.github.io website reflects the `master` branch, but not the `source` branch.

## How can this issue be closed?
This issue can be closed when a GitHub Actions Workflow has been added to this repository that builds the jekyll website and pushes the generated files to the `master` branch.

Alternatively, if we switch the github pages deployment branch to `source` we may not have to make a workflow at all.

### PR DESCRIPTION
**Pull request by yardasol**
## Summary of changes

This PR adds a workflow file to autodeploy the arfc.github.io website whenever the `source` branch is updated. This PR also adds a Gemfile to the repository.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issues and PRs

- Issue: closes #247 

## Associated Developers

- Dev: @munkm 

## Checklist for Reviewers

Reviewers should use [this link](/manual/guides/pull_requests) to get to the 
Review Checklist before they begin their review.

### CODE REVIEW

**Review by nsryan2 — COMMENTED** [review]
I don't have experience with workflows like this, so I might not be the best person to review this. The Gemfile looks good to me though, and the parts in the workflow seem to make sense

**Comment by yardasol** [comment]
> I don't have experience with workflows like this, so I might not be the best person to review this. The Gemfile looks good to me though, and the parts in the workflow seem to make sense. Thank you for taking this on though! This might be in @munkm's power, but it's also possible to change the branch that GitHub pages deploy from, which might be a more straightforward way to address this issue.

That's a nice idea, but unfortunately this won't satisfy our needs for the following reasons:

1. While GitHub Pages has Jekyll support built-in, it only supports a select few Gems. `jekyll-scholar`, which the website uses is unfortunately not one of them.

2. I believe that in order to have the `arfc.github.io` domain, Pages needs to deploy from the `master` branch. If we try to deploy from `source` or a `gh-pages` branch, the new URL would be `arfc.github.io/arfc.github.io`, which is not what we want.

Because of these two facts, we must use GitHub Actions to create a workflow that builds the site from `source` and deploys to `master`.

**Comment by munkm** [comment]
What @yardasol outlined regarding gems and gh-pages is my recollection as well. I believe it wouldn't be too hard to set up an action to use the `rake publish` command on merge of a PR. But I just haven't had the chance to test it out. If you look back in the history of the `source` branch, you'll see reverted commits from more than one person who accidentally published there rather than to master. 

@yardasol do you have a version of this workflow running on your personal account so we can verify all of the html pages are built as expected with the deploy? I don't see the rakefile referenced here and it does have build directions for the site.

**Review by munkm — APPROVED** [review]
I like this workflow! 🤞 that it works

**Pull request merged**
