### PR TITLE
Website Change (Photo)

### PR DESCRIPTION
**Pull request by datw0258**
## Summary of changes

Updated Photo to be square

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issues and PRs

- Issue: #

## Associated Developers

- Dev: @

### CODE REVIEW

**Comment by katyhuff** [comment]
Thanks @datw0258 . Here are some issues with this PR.

- [ ]  Please request me (or someone) as a reviewer if you submit a PR. (otherwise, we'll never know it's up... we need a notification).
- [ ] Your image has the extension PNG, but it's much more common to use png, so please change the name of the file with `git mv` to atwaterd.png
- [ ] Much more importantly, the metadata file calls the file "atwaterd.jpg," so the photo doesn't appear because atwater.jpg doesn't exist. To fix this, please change the metadata file to read "atwaterd.png"
- [ ] Finally, your photo is sideways. If you do the above three things, you'll see the following:

image

You are welcome to remain sideways, but I would recommend being upright if you can.

**Comment by datw0258** [comment]
I believe I have solved the problem (squaring the image, straightening the image, and renaming the image). Please let me know if there are any more issues (with the file or the Pull Request)

**Comment by katyhuff** [comment]
Please look here at the PR online: This branch has conflicts.

**Comment by katyhuff** [comment]
(perhaps this is related to using the web interface rather than using github on the command line?) Please converse with the graduate students to debug.

**Comment by katyhuff** [comment]
@datw0258 ^

**Comment by datw0258** [comment]
I will delete and re-upload from the command line to see if this fixes the bug today

**Pull request closed without merging**
