### PR TITLE
Add @yardasol GitHub link

### PR DESCRIPTION
**Pull request by yardasol**
## Summary of changes
This PR adds a link to @yardasol 's GitHub page.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Associated Developers

- Dev: @munkm 

## Checklist for Reviewers

Reviewers should use [this link](/manual/guides/pull_requests) to get to the 
Review Checklist before they begin their review.

### CODE REVIEW

**Review by munkm — COMMENTED** [review]
Looks good to me!

**Comment by munkm** [comment]
@yardasol even though this is trivial, please do not self-merge PRs without a review. This is not a good practice.

**Comment by yardasol** [comment]
@munkm I was going off of the directions under the [guide on adding oneself to the website](https://arfc.github.io/manual/guides/website):

>If you’re feeling confident, you can skip the pull request. Instead, you can just push changes to the website directly with the command rake publish. Only do this if you don’t need anyone to double check your work.

I did indeed feel confident about my addition, so thought it would be fine to merge.

On closer inspection, perhaps I should have done `rake publish` instead of making a pull request. Regardless, I agree with you that merging changes on a repo like this without secondary review is isn't a good practice. Perhaps we should modify the instructions on that page to reflect this?

**Comment by munkm** [comment]
Ooooh thank you for reminding me about this section.

I'm of two minds about this. The rake publish command is helpful, but it's easy to make mistakes. We can always revert the publish if it's incorrect (the last revert was my own commit), but maybe we shouldn't encourage it. I do trust you all to do the right thing, but I also think it's great practice for everybody to review PRs, even "easy" ones. 

My vote would be to remove these instructions. What do you think?

**Pull request merged**
