### PR TITLE
Adds 2019 I2CNER report

### PR DESCRIPTION
**Pull request by anshchaube**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issues and PRs

- Issue: #

## Associated Developers

- Dev: @

### CODE REVIEW

**Comment by katyhuff** [comment]
This PDF seems to be missing many of the fixes that you checked off here: https://github.com/arfc/i2cner/issues/81#issuecomment-492334494. 

The tables are all still missing titles, the sections include bare bullets... etc. 

Why were these ever checked off if they were not completed?

**Comment by achubbz** [comment]
I didn't commit the right tex/pdf file to either repository. Should be fixed now.

**Comment by katyhuff** [comment]
Please look over this a little more carefully once again. The tables 3,4,&5 are not mentioned in the text. It's clear you expect them to appear right after the hanging colons on page 4. But latex moves tables around. Instead of the hanging colons, please refer directly to the tables. 

Since these edits are the same edits I recommended before and that were checked off (i.e. all tables and figures should be referred to in the text), I'm not inclined to review this again until you're 100% confident it has satisfied all of the corrections that I have already requested. Please, take some time to look this over carefully before sending it back to me.

**Comment by katyhuff** [comment]
Here is the spot on page 4 to which I'm referring: 

image

**Comment by achubbz** [comment]
I think all these issues are fixed now.

**Pull request merged**
