### PR TITLE
to address issue #6

### LINKED ISSUE #6: Greeted with a lot of empty space when navigating to site
Observed with both Firefox and Chromium: upon initially opening web-pages, virtually no content appears on the screen, as observed in the attached screen shot. This is true for the home page, research page, people page, etc. Perhaps it would be nice (if possible) to move content up the page so that the navigator gets to see a healthy amount before s/he even starts scrolling. Just seems currently like there's a lot of initially empty, under-utilized space. I can listen to counter-arguments though!

web_page_screenshot

### PR DESCRIPTION
**Pull request by katyhuff**
to resolve #6

### CODE REVIEW

**Comment by katyhuff** [comment]
going to merge this myself.

**Comment by lindsayad** [comment]
@katyhuff Were you waiting for me to merge it? This is the first time I've been on a project I'm not leading where I'm an admin...should I feel free to merge other's PRs after a good inspection?

**Comment by katyhuff** [comment]
Aha! Yes, I suppose I was (no big deal though since it's just the website and not actual software). I'm used to projects with a workflow in which every PR gets a review by someone with push rights (and didn't make the PR in the first place). It's fairly common, as workflows go, in the open source communitiy, but there can be issues when people are low on time or when the hierarchy is quite imbalanced. I supposed I would like to see this as a general norm in the group for collaborative work, but for projects where you're the lead dev, I'd say you definitely should go with whatever workflow you prefer.

**Comment by katyhuff** [comment]
(I should make some documentation about this somewhere... maybe in the guides... or maybe this is the kind of thing that emerges as research groups age collectively... hm... )

**Comment by lindsayad** [comment]
I definitely have no issue with doing the review; in fact it's exciting 
to be part of truly collaborative work. Just wanted to make sure what 
you're looking for. Now I know!

**Comment by katyhuff** [comment]
Excellent!

**Pull request merged**
