### PR TITLE
adds a photo of Mitchell Whalen

### PR DESCRIPTION
**Pull request by mitchellwhalen**
## Summary of changes

Adding photo and bio to website

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issues and PRs

- Issue: #

## Associated Developers

- Dev: @

### CODE REVIEW

**Comment by katyhuff** [comment]
Just for the future:
Assign me as a "reviewer" in the future (the first button) when you want a PR review from me.

image


Will review asap.

**Comment by mitchellwhalen** [comment]
Am I clear to merge this request or are only you supposed to merge?

**Comment by katyhuff** [comment]
Neither.
Please wait.

**Comment by katyhuff** [comment]
Sorry for the previous curt response. I was on my phone. 

This is the issue mitchell... you need to add yourself to people.yml as well as add your photo to the repo. Did you read the instructions? arfc.github.io/manual/guides/website

**Comment by mitchellwhalen** [comment]
I believe I did edit the people.yml

**Comment by katyhuff** [comment]
You didn't commit the change. The file is not in this PR. You can see the file changes here:

https://github.com/arfc/arfc.github.io/pull/139/files

**Pull request closed without merging**
