### PR TITLE
Add moltres subdirectory

### PR DESCRIPTION
**Pull request by lindsayad**
I don't know if this is what you were thinking of for the doxygen. I essentially just copied the built html directory after running `doxygen ...` in my moltres directory. This is not an automated process obviously. Maybe you were thinking of something automated.

### CODE REVIEW

**Comment by katyhuff** [comment]
Thanks!! As you guessed... I do want to avoid having 1000+ html files in the source directory of this repository.

Here's a thought:

- For the Doxygen API docs, create a script in moltres that builds the doxygen html and places it in the gh-pages branch of the arfc/moltres repository. That way, Doxygen api info will always be at the link arfc.github.io/moltres. AND, updates to moltres can push changes to the moltres api docs without impacting the arfc repository.

- This URL obviously clashes with the moltres directory that you've just created. Instead, put all that stuff in a directory like "/research/moltres"

Then, the theory URL will be arfc.github.io/research/moltres and the doxygen url will be arfc.github.io/moltres.

**Comment by lindsayad** [comment]
Haha what could be better than a jillion files! Alright will do

**Comment by lindsayad** [comment]
Alright, doxygen removed and github pages set up on arfc/moltres

**Comment by katyhuff** [comment]
Excellent ! Merging! 
(gh-pages branch doesn't appear at arfc/moltres yet.. maybe I'm missing something. )

**Comment by katyhuff** [comment]
When I left that comment, I got a 404 at arfc.github.io/moltres. But, I see it now.

**Pull request merged**
